### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by deavmi** [deavmi/DuckIt#3]
Must complete the following below.

<hr>

**TODO List:**

- [x] [Add `--config` argument to allow user to change his/her browser.](https://github.com/deavmi/DuckIt/issues/2)
- [x] [Testing](https://github.com/deavmi/DuckIt/issues/1)
- [x] [Issue when running command.](https://github.com/deavmi/DuckIt/issues/4)

**Comment by deavmi** [comment]
Everyhign has seemed to chekc out well and been tested on my Arch/Antergos testbench, so ya, release time is near, I am thinking tomorrow, will be the release of **DuckIt** and many variants.

**Comment by deavmi** [comment]
All *variants are up**:

* [GoogIt](https://github.com/deavmi/GoogIt)
* [HooIt](https://github.com/deavmi/HooIt)
* [BingIt](https://github.com/deavmi/BingIt)

**Comment by deavmi** [comment]
Might do a little test on y side, but if i recall, everything was working.
